# Generated by Django 4.2.2 on 2023-07-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('nombre_autor', models.CharField(max_length=150, verbose_name='nombre_autor')),
                ('tipo', models.IntegerField(verbose_name='tipo')),
                ('estado', models.IntegerField(verbose_name='estado')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='img')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TiposObras',
            fields=[
                ('id_tipo', models.AutoField(db_column='id_tipo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
